version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:80"
    depends_on:
      - identity-server
      - master-data
  identity-server:
    build:
      context: ./identity-server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    networks:
      - app-network
  master-data:
    build: ./services/master-data
    ports:
      - "5002:80"
    depends_on:
      - sqlserver
      - rabbitmq
  hrm:
    build: ./services/hrm
    ports:
      - "5003:80"
    depends_on:
      - sqlserver
      - rabbitmq
      - redis
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge 